{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "llm-rag-chart.fullname" . }}
  annotations: {{ toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  rules:
  - host: {{ .Values.ingress.hosts[0].host }}
    http:
      paths:
      - path: {{ .Values.ingress.hosts[0].paths[0].path }}
        pathType: Prefix
        backend:
          service:
            name: {{ include "llm-rag-chart.fullname" . }}-llm
            port:
              number: 80
{{- end }}