apiVersion: v1
kind: Service
metadata:
  name: {{ include "llm-rag-chart.fullname" . }}-llm
spec:
  selector:
    app: {{ include "llm-rag-chart.name" . }}-llm
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.llm.port }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "llm-rag-chart.fullname" . }}-vector-db
spec:
  selector:
    app: {{ include "llm-rag-chart.name" . }}-vector-db
  ports:
    - protocol: TCP
      port: 8081
      targetPort: {{ .Values.vectorDb.port }}